name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install nix
        uses: cachix/install-nix-action@master
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/f8e2ebd66d097614d51a56a755450d4ae1632df1.tar.gz
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build website
        run: nix build -L
      - name: Upload artifact
        uses: actions/upload-pages-artifact@main
        with:
          path: result/
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@main
